import Foundation
import AppKit

/// 轮询系统剪贴板,把新内容交给 `HistoryStore`。
///
/// macOS 没有剪贴板变化的推送通知,只能定时检查 `NSPasteboard.changeCount`。
final class ClipboardMonitor {

    private let store: HistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int

    /// nspasteboard.org 的事实标准标记:被标记的内容不应被历史记录工具收录。
    /// 密码管理器(1Password 等)复制密码时会打上 ConcealedType。
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    init(store: HistoryStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start(interval: TimeInterval = 0.5) {
        timer?.invalidate()
        let t = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 把"当前剪贴板状态"标记为已知。我们自己写回剪贴板后调用,避免把自己写入的内容
    /// 当成新条目造成回环。
    func acknowledgeCurrentState() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    // MARK: - 轮询

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        // 敏感/瞬态内容 → 跳过
        if let types = pb.types, types.contains(where: { Self.ignoredTypes.contains($0) }) {
            return
        }

        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // 同时存在临时 file-url 与像素数据时优先保留可持久化的图片。
        if let content = readImage(pb) ?? readFiles(pb) ?? readText(pb) {
            _ = store.add(content, sourceApp: sourceApp)
        }
    }

    private func readFiles(_ pb: NSPasteboard) -> CapturedContent? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pb.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              !urls.isEmpty else { return nil }
        return .files(urls.map { $0.path })
    }

    private func readImage(_ pb: NSPasteboard) -> CapturedContent? {
        // 统一规整成 PNG 落盘:优先直接取 PNG,否则把 TIFF 转 PNG。
        var png: Data?
        if let d = pb.data(forType: .png), d.count <= HistoryStore.maxImageBytes {
            png = d
        } else if let tiff = pb.data(forType: .tiff),
                  tiff.count <= HistoryStore.maxImageBytes,
                  let rep = NSBitmapImageRep(data: tiff) {
            png = rep.representation(using: .png, properties: [:])
        }
        guard let data = png, data.count <= HistoryStore.maxImageBytes else { return nil }

        var pixelSize: String?
        if let rep = NSBitmapImageRep(data: data) {
            pixelSize = "\(rep.pixelsWide)×\(rep.pixelsHigh)"
        }
        return .image(data, pixelSize: pixelSize)
    }

    private func readText(_ pb: NSPasteboard) -> CapturedContent? {
        guard let s = pb.string(forType: .string), !s.isEmpty,
              s.utf8.count <= HistoryStore.maxTextBytes else { return nil }
        return .text(s)
    }
}
